# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from draw import FilterHandler, BlurHandler, default_image


class ClickableLabel(QtWidgets.QLabel):
    clicked = QtCore.pyqtSignal()

    def __init__(self, parent):
        super().__init__(parent)

    def mousePressEvent(self, event):
        self.clicked.emit()
        QtWidgets.QLabel.mousePressEvent(self, event)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 600)
        MainWindow.setMinimumSize(QtCore.QSize(700, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setMinimumSize(QtCore.QSize(0, 350))
        self.image_label.setText("")
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.verticalLayout_6.addWidget(self.image_label)

        self.menu_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.menu_tab.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menu_tab.setElideMode(QtCore.Qt.ElideNone)
        self.menu_tab.setObjectName("menu_tab")

        self.adjusting_tab = QtWidgets.QWidget()
        self.adjusting_tab.setObjectName("adjusting_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.adjusting_tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.brightness_label = QtWidgets.QLabel(self.adjusting_tab)
        self.brightness_label.setAlignment(QtCore.Qt.AlignCenter)
        self.brightness_label.setObjectName("brightness_label")
        self.verticalLayout_7.addWidget(self.brightness_label)
        self.brightness_slider = QtWidgets.QSlider(self.adjusting_tab)
        self.brightness_slider.setMaximum(100)
        self.brightness_slider.setProperty("value", 50)
        self.brightness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.brightness_slider.setObjectName("brightness_slider")
        self.verticalLayout_7.addWidget(self.brightness_slider)
        self.contrast_label = QtWidgets.QLabel(self.adjusting_tab)
        self.contrast_label.setAlignment(QtCore.Qt.AlignCenter)
        self.contrast_label.setObjectName("contrast_label")
        self.verticalLayout_7.addWidget(self.contrast_label)
        self.contrast_slider = QtWidgets.QSlider(self.adjusting_tab)
        self.contrast_slider.setMaximum(100)
        self.contrast_slider.setProperty("value", 50)
        self.contrast_slider.setOrientation(QtCore.Qt.Horizontal)
        self.contrast_slider.setObjectName("contrast_slider")
        self.verticalLayout_7.addWidget(self.contrast_slider)
        self.sharpness_label = QtWidgets.QLabel(self.adjusting_tab)
        self.sharpness_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sharpness_label.setObjectName("sharpness_label")
        self.verticalLayout_7.addWidget(self.sharpness_label)
        self.sharpness_slider = QtWidgets.QSlider(self.adjusting_tab)
        self.sharpness_slider.setMaximum(100)
        self.sharpness_slider.setProperty("value", 50)
        self.sharpness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sharpness_slider.setObjectName("sharpness_slider")
        self.verticalLayout_7.addWidget(self.sharpness_slider)
        self.menu_tab.addTab(self.adjusting_tab, "")

        self.crop_tab = QtWidgets.QWidget()
        self.crop_tab.setObjectName("crop_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.crop_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.crop_top_label = QtWidgets.QLabel(self.crop_tab)
        self.crop_top_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.crop_top_label.setAlignment(QtCore.Qt.AlignCenter)
        self.crop_top_label.setObjectName("crop_top_label")
        self.verticalLayout_4.addWidget(self.crop_top_label)
        self.crop_top_slider = QtWidgets.QSlider(self.crop_tab)
        self.crop_top_slider.setMinimum(1)
        self.crop_top_slider.setMaximum(100)
        self.crop_top_slider.setProperty("value", 100)
        self.crop_top_slider.setOrientation(QtCore.Qt.Horizontal)
        self.crop_top_slider.setObjectName("crop_top_slider")
        self.verticalLayout_4.addWidget(self.crop_top_slider)
        self.crop_bottom_label = QtWidgets.QLabel(self.crop_tab)
        self.crop_bottom_label.setAlignment(QtCore.Qt.AlignCenter)
        self.crop_bottom_label.setObjectName("crop_bottom_label")
        self.verticalLayout_4.addWidget(self.crop_bottom_label)
        self.crop_bottom_slider = QtWidgets.QSlider(self.crop_tab)
        self.crop_bottom_slider.setMinimum(1)
        self.crop_bottom_slider.setMaximum(100)
        self.crop_bottom_slider.setProperty("value", 100)
        self.crop_bottom_slider.setOrientation(QtCore.Qt.Horizontal)
        self.crop_bottom_slider.setObjectName("crop_bottom_slider")
        self.verticalLayout_4.addWidget(self.crop_bottom_slider)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.crop_left_label = QtWidgets.QLabel(self.crop_tab)
        self.crop_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.crop_left_label.setObjectName("crop_left_label")
        self.verticalLayout_5.addWidget(self.crop_left_label)
        self.crop_left_slider = QtWidgets.QSlider(self.crop_tab)
        self.crop_left_slider.setMinimum(1)
        self.crop_left_slider.setMaximum(100)
        self.crop_left_slider.setProperty("value", 100)
        self.crop_left_slider.setOrientation(QtCore.Qt.Horizontal)
        self.crop_left_slider.setObjectName("crop_left_slider")
        self.verticalLayout_5.addWidget(self.crop_left_slider)
        self.crop_right_label = QtWidgets.QLabel(self.crop_tab)
        self.crop_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.crop_right_label.setObjectName("crop_right_label")
        self.verticalLayout_5.addWidget(self.crop_right_label)
        self.crop_right_slider = QtWidgets.QSlider(self.crop_tab)
        self.crop_right_slider.setMinimum(1)
        self.crop_right_slider.setMaximum(100)
        self.crop_right_slider.setProperty("value", 100)
        self.crop_right_slider.setOrientation(QtCore.Qt.Horizontal)
        self.crop_right_slider.setObjectName("crop_right_slider")
        self.verticalLayout_5.addWidget(self.crop_right_slider)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.menu_tab.addTab(self.crop_tab, "")

        self.rotate_tab = QtWidgets.QWidget()
        self.rotate_tab.setObjectName("rotate_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rotate_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.flip_horizontal_button = QtWidgets.QPushButton(self.rotate_tab)
        self.flip_horizontal_button.setObjectName("flip_horizontal_button")
        self.verticalLayout.addWidget(self.flip_horizontal_button)
        self.flip_vertical_button = QtWidgets.QPushButton(self.rotate_tab)
        self.flip_vertical_button.setObjectName("flip_vertical_button")
        self.verticalLayout.addWidget(self.flip_vertical_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rotate_plus90_button = QtWidgets.QPushButton(self.rotate_tab)
        self.rotate_plus90_button.setObjectName("rotate_plus90_button")
        self.verticalLayout_2.addWidget(self.rotate_plus90_button)
        self.rotate_minus90_button = QtWidgets.QPushButton(self.rotate_tab)
        self.rotate_minus90_button.setObjectName("rotate_minus90_button")
        self.verticalLayout_2.addWidget(self.rotate_minus90_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.menu_tab.addTab(self.rotate_tab, "")

        self.filters_tab = QtWidgets.QWidget()
        self.filters_tab.setObjectName("filters_tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.filters_tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.default_fliter_label = ClickableLabel(self.filters_tab)
        self.default_fliter_label.setMaximumSize(QtCore.QSize(150, 150))
        self.default_fliter_label.setStyleSheet("border: 1px solid blue")
        self.default_fliter_label.setText("")
        self.default_fliter_label.setObjectName("default_fliter_label")
        self.default_fliter_label.func = default_image
        self.default_fliter_label.flag = False
        self.default_fliter_label.name = 'По_умолчанию'
        self.horizontalLayout_4.addWidget(self.default_fliter_label)
        self.black_white_filter_label = ClickableLabel(self.filters_tab)
        self.black_white_filter_label.setMaximumSize(QtCore.QSize(150, 150))
        self.black_white_filter_label.setStyleSheet("border: 1px solid gray")
        self.black_white_filter_label.setText("")
        self.black_white_filter_label.setObjectName("black_white_filter_label")
        self.black_white_filter_label.func = FilterHandler.black_white
        self.black_white_filter_label.flag = False
        self.black_white_filter_label.name = 'Черно-белый'
        self.horizontalLayout_4.addWidget(self.black_white_filter_label)
        self.negative_filter_label = ClickableLabel(self.filters_tab)
        self.negative_filter_label.setMaximumSize(QtCore.QSize(150, 150))
        self.negative_filter_label.setStyleSheet("border: 1px solid gray")
        self.negative_filter_label.setText("")
        self.negative_filter_label.setObjectName("negative_filter_label")
        self.negative_filter_label.func = FilterHandler.negative
        self.negative_filter_label.flag = False
        self.negative_filter_label.name = 'Негатив'
        self.horizontalLayout_4.addWidget(self.negative_filter_label)
        self.sepia_filter_label = ClickableLabel(self.filters_tab)
        self.sepia_filter_label.setMaximumSize(QtCore.QSize(150, 150))
        self.sepia_filter_label.setStyleSheet("border: 1px solid gray")
        self.sepia_filter_label.setText("")
        self.sepia_filter_label.setObjectName("sepia_filter_label")
        self.sepia_filter_label.func = FilterHandler.sepia
        self.sepia_filter_label.flag = False
        self.sepia_filter_label.name = 'Сепия'
        self.horizontalLayout_4.addWidget(self.sepia_filter_label)
        self.menu_tab.addTab(self.filters_tab, "")

        self.blur_tab = QtWidgets.QWidget()
        self.blur_tab.setObjectName("blur_tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.blur_tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.default_blur_label = ClickableLabel(self.blur_tab)
        self.default_blur_label.setMinimumSize(QtCore.QSize(0, 0))
        self.default_blur_label.setMaximumSize(QtCore.QSize(150, 150))
        self.default_blur_label.setStyleSheet("border: 1px solid blue")
        self.default_blur_label.setText("")
        self.default_blur_label.setObjectName("default_blur_label")
        self.default_blur_label.func = default_image
        self.default_blur_label.flag = False
        self.default_blur_label.name = 'По_умолчанию'
        self.horizontalLayout_3.addWidget(self.default_blur_label)
        self.vertical_blur_label = ClickableLabel(self.blur_tab)
        self.vertical_blur_label.setMinimumSize(QtCore.QSize(0, 0))
        self.vertical_blur_label.setMaximumSize(QtCore.QSize(150, 150))
        self.vertical_blur_label.setStyleSheet("border: 1px solid gray")
        self.vertical_blur_label.setText("")
        self.vertical_blur_label.setObjectName("vertical_blur_label")
        self.vertical_blur_label.func = BlurHandler.vertical_blur
        self.vertical_blur_label.flag = False
        self.vertical_blur_label.name = 'Вертикальное размытие'
        self.horizontalLayout_3.addWidget(self.vertical_blur_label)
        self.horizontal_blur_label = ClickableLabel(self.blur_tab)
        self.horizontal_blur_label.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontal_blur_label.setMaximumSize(QtCore.QSize(150, 150))
        self.horizontal_blur_label.setStyleSheet("border: 1px solid gray")
        self.horizontal_blur_label.setText("")
        self.horizontal_blur_label.setObjectName("horizontal_blur_label")
        self.horizontal_blur_label.func = BlurHandler.horizontal_blur
        self.horizontal_blur_label.flag = False
        self.horizontal_blur_label.name = 'Горизонтальное размытие'
        self.horizontalLayout_3.addWidget(self.horizontal_blur_label)
        self.menu_tab.addTab(self.blur_tab, "")
        self.verticalLayout_6.addWidget(self.menu_tab)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAddFilter = QtWidgets.QAction(MainWindow)
        self.actionAddFilter.setObjectName("actionAddFilter")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionAddFilter)
        self.menuEdit.addAction(self.actionReset)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.crop_sliders = [self.crop_left_slider, self.crop_right_slider, self.crop_top_slider,
                        self.crop_bottom_slider]
        self.adjusting_sliders = [self.brightness_slider, self.contrast_slider, self.sharpness_slider]
        self.filter_labels = [self.default_fliter_label,
                              self.sepia_filter_label, self.negative_filter_label, self.black_white_filter_label]
        self.blur_labels = [self.default_blur_label, self.vertical_blur_label, self.horizontal_blur_label]

        self.retranslateUi(MainWindow)
        self.menu_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Photo Editor"))
        self.brightness_label.setText(_translate("MainWindow", "Яркость"))
        self.contrast_label.setText(_translate("MainWindow", "Контраст"))
        self.sharpness_label.setText(_translate("MainWindow", "Резкость"))
        self.menu_tab.setTabText(self.menu_tab.indexOf(self.adjusting_tab), _translate("MainWindow", "Регулировка"))
        self.crop_top_label.setText(_translate("MainWindow", "Верхняя сторона:"))
        self.crop_bottom_label.setText(_translate("MainWindow", "Нижняя сторона:"))
        self.crop_left_label.setText(_translate("MainWindow", "Левая сторона:"))
        self.crop_right_label.setText(_translate("MainWindow", "Правая сторона:"))
        self.menu_tab.setTabText(self.menu_tab.indexOf(self.crop_tab), _translate("MainWindow", "Обрезать"))
        self.flip_horizontal_button.setText(_translate("MainWindow", "Развернуть горизонтально"))
        self.flip_vertical_button.setText(_translate("MainWindow", "Развернуть вертикально"))
        self.rotate_plus90_button.setText(_translate("MainWindow", "Повернуть на +90°"))
        self.rotate_minus90_button.setText(_translate("MainWindow", "Повернуть на -90°"))
        self.menu_tab.setTabText(self.menu_tab.indexOf(self.rotate_tab), _translate("MainWindow", "Повернуть"))
        self.menu_tab.setTabText(self.menu_tab.indexOf(self.filters_tab), _translate("MainWindow", "Фильтры"))
        self.menu_tab.setTabText(self.menu_tab.indexOf(self.blur_tab), _translate("MainWindow", "Размытие"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuEdit.setTitle(_translate("MainWindow", "Правка"))
        self.actionOpen.setText(_translate("MainWindow", "Открыть"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Сохранить"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionAddFilter.setText(_translate("MainWindow", "Добавить фильтр"))
        self.actionReset.setText(_translate("MainWindow", "Сброс"))
        self.actionReset.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionUndo.setText(_translate("MainWindow", "Шаг назад"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Шаг вперед"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))

    def add_filter_label(self, func):
        exec(f'self.{func.__name__}_label = ClickableLabel(self.filters_tab)')
        eval(f'self.{func.__name__}_label.setMaximumSize(QtCore.QSize(150, 150))')
        eval(f'self.{func.__name__}_label.setStyleSheet("border: 1px solid gray")')
        eval(f'self.{func.__name__}_label.setText("")')
        eval(f'self.{func.__name__}_label.setObjectName("self.{func.__name__}_label")')
        eval(f'self.horizontalLayout_4.addWidget(self.{func.__name__}_label)')
        return eval(f'self.{func.__name__}_label')
